apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
<<<<<<< HEAD
          image: chhatreshpatel/myapp:latest
          ports:
            - containerPort: 80
=======
          image: chhatreshpatel/myapp:latest
          ports:
            - containerPort: 80
>>>>>>> a33d5fb (update deployment)
